### ISSUE TITLE
Rename callback should handle global symbols

### ISSUE THREAD

**Issue by velteyn** [cyberkaida/reverse-engineering-assistant#30]
Hello I want to rename a function, then I right click on reva->Rename over the function name and I obtain this:

![immagine](https://github.com/cyberkaida/reverse-engineering-assistant/assets/1019294/af69840e-670f-4d07-8f22-8dd5f5457ac4)

**Comment by velteyn** [comment]
if you need the program I can provide it

**Comment by cyberkaida** [comment]
Thank you for this bug report.

The issue is that the right click rename command should detect a high symbol or a global symbol. I will update the handler to detect this case and finish the rename global symbol command to allow renaming functions.

I apologise for the inconvenience, you will have a better time with the chat functions. I am currently working hard on the Ghidra plugin, so there will be bugs and unfinished features for a few more weeks.

**Comment by cyberkaida** [comment]
The global symbol rename should work now. If we don't support renaming a specific thing, we will print to the log.

If something fails to rename, please let me know!

You should be able to right click and press rename on global symbols (functions, variables) and on things in the decompilation. I do not support everything in the listing view yet, but this should cover most cases.

**Comment by velteyn** [comment]
This weeknd I'll give it a try , thank you
